# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1f5847c48f6ac18980ed1d78a512d30c702bb8fa1eb2fcd4b89925239933b04213575465cb58e76d23c8805a9d99b2f7eac2812296d88c796d8756f737d6cff

test:
  secret_key_base: 3e3925613adb96a3eb25af34c3546d3047a5cc111509a9cee73e32bf38f4b56679117c7439bce78caba05efb81013ef7d7107ed7e5b09ef8555650a92895988a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
